name: BackEnd CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build containers
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml build

          
      - name: Start services
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d   
          
      - name: Lint & format check
        run: |
          docker compose exec backend black --check .
          docker compose exec backend isort --check-only .
          docker compose exec backend flake8     
          
      - name: Run migrations
        run: |
          docker compose exec backend python manage.py migrate
          
      - name: Run tests
        run: |
          docker compose exec backend python manage.py test
          
      - name: Shutdown
        if: always()
        run: |
          docker compose down -v    
    
      
          
          
        
        
    
